### ISSUE TITLE
Bilingual street name

### ISSUE THREAD

**Issue by jbelien** [RobinLinde/ESN-edit#4]
In Brussels, all street names are bilingual.

The name "extraction" works fine but the query is made on "person name - person name" instead of just "person name".

---

Example: https://edit.equalstreetnames.eu/?type=way&id=182008773

It looks for `Jules Cockx - Jules Cockx` ([query](https://www.wikidata.org/w/api.php?action=wbsearchentities&search=%20Jules%20Cockx%20-%20Jules%20Cockx&language=en&limit=20&continue=0&format=json&uselang=en&type=item&origin=*)) instead of just `Jules Cockx` ([query](https://www.wikidata.org/w/api.php?action=wbsearchentities&search=%20Jules%20Cockx&language=en&limit=20&continue=0&format=json&uselang=en&type=item&origin=*))

**Comment by RobinLinde** [comment]
That was actually something I was thinking about yesterday, I guess using one of the name:xx tags would probably be better if they exist. #6 would also be handy to be able to replace the search term manually

**Comment by jbelien** [comment]
> [...], I guess using one of the name:xx tags would probably be better if they exist.

Yes, I think that's indeed an excellent idea.
So you can also use the `language` parameter in Wikidata API to the correct language (instead of the default `en`).

**Comment by RobinLinde** [comment]
@jbelien It should now use the first `name:xx` tag if any `name:xx` tags are found, and select language based on that.
